### ISSUE TITLE
`JSONTypeError`,  `JSONObjectError`, `JSONParserError`, and `JSONArrayError` don't inherit from `std::exception` 

### ISSUE THREAD

**Issue by lethalbit** [DX-MON/rSON#4]
As per the title, the errors thrown by rSON, `JSONTypeError`,  `JSONObjectError`, `JSONParserError`, and `JSONArrayError` don't inherit from `std::exception` making it impossible to catch all of them in a single try block with `catch (std::exception& e) { ... }`

**Comment by DX-MON** [comment]
This should now be fixed as of 991eca2. Don't forget when catching via `std::exception` that it is preferred you catch a `const std::exception &`.
